<?php

namespace Nemundo\Pdf\Document;

use Nemundo\Core\Base\AbstractDocument;
use Nemundo\Pdf\Base\AbstractPdfObject;

abstract class AbstractPdfDocument extends AbstractDocument
{


    public $filename;

    /**
     * @var AbstractPdfObject[]
     */
    private $pdfObjectList = [];


    public function writeFile()
    {

        $this->load();

    }


    public function addObject(AbstractPdfObject $pdfObject)
    {

        $this->pdfObjectList[] = $pdfObject;
        return $this;

    }


    public function render()
    {
        parent::render(); // TODO: Change the autogenerated stub
    }


    private function load()
    {

        require(__DIR__ . '/../../lib/fpdf/fpdf.php');

        /*$filename = (new \Nemundo\Project\Path\TmpPath())
            ->addPath('report.pdf')
            ->getFullFilename();*/

        /*$fontFilename = (new \Nemundo\Project\Path\TmpPath())
            ->addPath('Villa.php')
            ->getFullFilename();

        $filename = (new \Nemundo\Project\Path\TmpPath())
            ->addPath('report.pdf')
            ->getFullFilename();

        $imgFilename = (new \Nemundo\Project\Path\TmpPath())
            ->addPath('report.jpg')
            ->getFullFilename();*/

        $fpdf = new \FPDF();
        $fpdf->AddPage();

        //$pdf->AddPage('L',[200,100]);

        //$pdf->AddFont('Villa','',$fontFilename);

        /*$logoFilename =  (new \Nemundo\Project\Path\TmpPath())
            ->addPath('logo.png')
            ->getFullFilename();*/

        foreach ($this->pdfObjectList as $pdfObject) {
            $pdfObject->renderPdf($fpdf);
        }


        $fpdf->Output('F', $this->filename);


    }


    public function exportJpg($imageFilename)
    {

        $this->exportImage($imageFilename,'jpg');

        /*$im = new \Imagick($this->filename);  // new imagick('file.pdf[0]');
        $im->setImageFormat('jpg');
        $im->writeImage($imageFilename);*/

        return $this;


    }


    public function exportPng($imageFilename)
    {

        $this->exportImage($imageFilename,'jpg');
        return $this;


        /*$im = new \Imagick('D:\Tmp_Git\politik\tmp\report.pdf');  // new imagick('file.pdf[0]');
$im->setImageFormat('jpg');
$im->writeImage($imgFilename);*/


    }



    private function exportImage($filename, $fileExtension) {

        $im = new \Imagick($this->filename);  // new imagick('file.pdf[0]');
        $im->setImageFormat($fileExtension);
        $im->writeImage($filename);

    }

}