<?php

namespace Nemundo\Pdf\Document;

use Nemundo\Core\Base\AbstractDocument;

class PdfDocument extends AbstractPdfDocument
{


    /*public $filename;

    public function writeFile()
    {

        $this->load();

    }

    public function render()
    {
        parent::render(); // TODO: Change the autogenerated stub
    }


    private function load() {

        require(__DIR__.'/../../lib/fpdf/fpdf.php');

        /*$filename = (new \Nemundo\Project\Path\TmpPath())
            ->addPath('report.pdf')
            ->getFullFilename();*/

        /*$fontFilename = (new \Nemundo\Project\Path\TmpPath())
            ->addPath('Villa.php')
            ->getFullFilename();

        $filename = (new \Nemundo\Project\Path\TmpPath())
            ->addPath('report.pdf')
            ->getFullFilename();

        $imgFilename = (new \Nemundo\Project\Path\TmpPath())
            ->addPath('report.jpg')
            ->getFullFilename();*/

    /*    $pdf = new \FPDF();
        //$pdf->AddPage('L',[200,100]);

        //$pdf->AddFont('Villa','',$fontFilename);

        /*$logoFilename =  (new \Nemundo\Project\Path\TmpPath())
            ->addPath('logo.png')
            ->getFullFilename();*/


     /*   $pdf->Output('F', $this->filename);


    }*/





}